# -*- coding: utf-8 -*-
"""word_setiment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nyUucZuibkdmrbEpJqF0RqsUt5NrMPAH
"""

import pandas as pd

# Define detailed sentiment scores for the words
detailed_sentiment_scores = {
    'best': 1, 'love': 1, 'amazing': 1, 'incredible': 1, 'fantastic': 1, 'outstanding': 1,
    'great': 0.9, 'brilliant': 0.9, 'wonderful': 0.9, 'awesome': 0.9, 'marvelous': 0.9,
    'superb': 0.9, 'happy': 0.8, 'enjoy': 0.8, 'exciting': 0.8, 'recommend': 0.7, 'positive': 0.7,
    'good': 0.6, 'like': 0.5,  # Positive words
    'film': 0, 'movie': 0, 'one': 0, 'time': 0, 'way': 0, 'people': 0, 'thing': 0, 'story': 0,
    'thought': 0, 'scene': 0, 'moment': 0, 'day': 0, 'part': 0, 'idea': 0, 'place': 0,
    'question': 0, 'group': 0, 'view': 0, 'role': 0,  # Neutral words
    'sad': -0.5, 'boring': -0.5, 'bad': -0.6, 'annoying': -0.6, 'dislike': -0.6, 'disappointed': -0.7,
    'negative': -0.7, 'dull': -0.7, 'poor': -0.8, 'regret': -0.8, 'unpleasant': -0.8, 'hate': -1,
    'worst': -1, 'awful': -1, 'terrible': -1, 'horrible': -1, 'horrendous': -1  # Negative words
}

# 1. Veri Okuma (Yorumlar içeren CSV dosyasını okuyoruz)
file_path = 'veriseti.csv'  # Yüklenen dosya yolu
df = pd.read_csv(file_path)

# 2. Detaylı Puanlama Fonksiyonu
def calculate_review_score(review):
    words = review.split()  # Yorumdaki kelimeleri ayırıyoruz
    score = 0

    for word in words:
        # Her kelimeye sayısal değer ataması
        score += detailed_sentiment_scores.get(word, 0)  # Eğer kelime listede yoksa 0 puan verir

    return score

# 3. Yorumları Puanlama
df['Review_Score'] = df['Lemmatized_Review'].apply(calculate_review_score)

# 4. Puanlara göre Etiketleme (Pozitif, Negatif, Nötr)
def label_sentiment_by_score(score):
    if score > 0:
        return 'Pozitif'
    elif score < 0:
        return 'Negatif'
    else:
        return 'Nötr'

df['Sentiment_Label'] = df['Review_Score'].apply(label_sentiment_by_score)

# 5. Sonuçları Görüntüleme
df[['Lemmatized_Review', 'Review_Score', 'Sentiment_Label']].head()  # İlk 5 yorumu ve etiketlerini görüntüleyin

# 6. Etiketli veriyi yeni bir dosyaya kaydetme
output_path = 'word_sentiment.csv'  # Çıktıyı kaydedeceğiniz yolu belirleyin
df.to_csv(output_path, index=False)

output_path  # Kaydedilen dosyanın yolunu döndürüyoruz

